# =========================================================
# 🌍 Application Info
# =========================================================
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/AuthenticationDatabase
    username: TravelApplication123
    password: TravelApplication123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 7000
            logger-level: basic

# =========================================================
# ⚙️ Server Configuration
# =========================================================
server:
  address: 0.0.0.0
  port: 9011
  servlet:
    context-path: /auth
  tomcat:
    connection-timeout: 10s
    max-threads: 150
    min-spare-threads: 20
    accept-count: 100
    max-connections: 2000

# =========================================================
# 🌐 External Service URLs
# =========================================================
services:
  employee:
    url: http://localhost:9010/ems
  policy:
    url: http://localhost:9012/policy
  travel-request:
    url: http://localhost:9015/travel-management
  workflow:
    url: http://localhost:9013/workflow

# =========================================================
# 🔑 JWT Configuration
# =========================================================
jwt:
  secret: MySuperSecureAesEncryptionKey123456
  expiration-seconds: 3600

# =========================================================
# 🧾 Logging
# =========================================================
logging:
  level:
    root: INFO
    com.bwc.auth_service: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

# =========================================================
# 📊 Actuator + Prometheus (Unified)
# =========================================================
management:
  server:
    port: 9111
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 30s
