# =========================================================
# 🌍 Application Info
# =========================================================
spring:
  application:
    name: employee-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/EmployeeDatabase
    username: TravelApplication123
    password: TravelApplication123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
          fetch_size: 100
        order_inserts: true
        order_updates: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s

# =========================================================
# ⚙️ Server Configuration
# =========================================================
server:
  address: 0.0.0.0
  port: 9010
  servlet:
    context-path: /ems
  tomcat:
    connection-timeout: 10s     # ✅ fixed (moved here from deprecated root)
    max-threads: 200
    min-spare-threads: 20
    accept-count: 200
    max-connections: 5000

# =========================================================
# 📘 Swagger / OpenAPI
# =========================================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true

# =========================================================
# 🌐 External Services (Feign)
# =========================================================
services:
  policy:
    url: http://localhost:9012/policy
  travel-request:
    url: http://localhost:9015/travel-management
  workflow:
    url: http://localhost:9013/workflow

# =========================================================
# 🧾 Logging
# =========================================================
logging:
  level:
    root: INFO
    com.bwc.employee_management_service: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# =========================================================
# 📊 Actuator (Unified & Modernized)
# =========================================================
management:
  server:
    port: 9110

  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,threaddump,heapdump

  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  prometheus:
    metrics:
      export:
        enabled: true   # ✅ replaced deprecated key
        step: 30s
